#!/bin/bash
set -euo pipefail

###
 # @file
 # This file processes 'stream.online' event notifications.
 #
 # When one of these events is encountered, Streamlink will be started for the
 # user who went online.
 #
 # Check the CONFIG section before using this script.
 ##

################################################################################
#                                   CONFIG                                     #
################################################################################

# Configure the OAuth token to pass to the Twitch API (optional).
#
# See https://github.com/clayfreeman/twitch-auth-token-sync for a way that
# developers can automatically get their 'auth-token' cookie value.
AUTH_TOKEN=$(cat "$HOME/.auth-token" 2>/dev/null || true)

# Configure where downloaded files will be saved.
DOWNLOAD_DIR="$HOME/archives"

# Configure the maximum number of download attempts.
MAX_ATTEMPTS=3

# Configure the naming pattern to use for downloaded files (without extension).
NAME='{time:%Y}/{time:%m}/{time:%d}/[{time:%H:%M:%S}] {title} ({id})'

# Configure the arguments for Streamlink.
# The output path will be nested beneath "$DOWNLOAD_DIR/$STREAM".
STREAMLINK_ARGS=(
  --default-stream=best
  --logdateformat='%Y-%m-%dT%H:%M:%S'
  --logformat='[{asctime}][{name}][{levelname}] {message}'
  --webbrowser=no
)
STREAMLINK_ARGS_DOWNLOAD=(
  --force
  --progress=no
  --retry-max=3
  --retry-open=3
  --retry-streams=3
  --twitch-disable-ads
)

# Configure the amount of time to wait for a lock (in seconds).
#
# This is useful to debounce multiple 'stream.online' events, while still
# affording some level of reliability for temporary disconnects.
TIMEOUT=300

################################################################################
#                                   SCRIPT                                     #
################################################################################

if STREAM=$(jq -cer 'select(.subscription.type == "stream.online") | .event.broadcaster_user_login')
then
  if [ -z "${DOWNLOAD_DIR:-}" ]
  then
    echo "Error: The required DOWNLOAD_DIR variable is missing." >&2
    exit 1
  fi

  if ! [[ "${MAX_ATTEMPTS:-}" =~ ^[0-9]+$ ]] || (( MAX_ATTEMPTS <= 0 ))
  then
    echo "Error: MAX_ATTEMPTS must be a positive integer." >&2
    exit 1
  fi

  if [ -z "${NAME:-}" ]
  then
    echo "Error: The required NAME variable is missing." >&2
    exit 1
  fi

  if [ -z "${STREAMLINK_ARGS:-}" ]
  then
    echo "Error: The required STREAMLINK_ARGS variable is missing." >&2
    exit 1
  fi

  if [ -z "${STREAMLINK_ARGS_DOWNLOAD:-}" ]
  then
    echo "Error: The required STREAMLINK_ARGS_DOWNLOAD variable is missing." >&2
    exit 1
  fi

  OUTDIR="$DOWNLOAD_DIR/$STREAM"

  LOCKFILE="$HOME/.$STREAM.lock"
  LOGFILE="$HOME/streamlink.log"

  URL="https://www.twitch.tv/$STREAM"

  if [ -n "${AUTH_TOKEN:-}" ]
  then
    STREAMLINK_ARGS+=(--twitch-api-header=Authorization="OAuth $AUTH_TOKEN")
  fi

  STREAMLINK_ARGS+=(--url="$URL")
  STREAMLINK_ARGS_DOWNLOAD+=("${STREAMLINK_ARGS[@]}" --output="$NAME".ts)

  if ! mkdir -p "$OUTDIR" || ! [ -w "$OUTDIR" ] || ! [ -x "$OUTDIR" ]
  then
    echo "Error: The output directory is not suitable." >&2
    exit 1
  fi

  cd "$OUTDIR"

  exec &> >(tee -a "$LOGFILE")
  exec {LOCK}<>"$LOCKFILE"
  flock -w "$TIMEOUT" $LOCK

  ATTEMPTS=0
  while true
  do
    echo "Downloading '$URL' [$((++ATTEMPTS))/$MAX_ATTEMPTS] ..." >&2
    streamlink "${STREAMLINK_ARGS_DOWNLOAD[@]}" || echo "Error: '$URL' download exited with non-zero code: $?" >&2

    if [ "$ATTEMPTS" -ge "$MAX_ATTEMPTS" ]
    then
      echo "'$URL' download attempts exhausted; exiting ..." >&2
      break
    elif ! streamlink "${STREAMLINK_ARGS[@]}" --stream-url &>/dev/null
    then
      echo "'$URL' is now offline." >&2
      break
    fi
  done

  shopt -s globstar nullglob
  for INPUT in **/*.ts
  do
    OUTPUT="${INPUT%.ts}.mp4"

    echo "Remuxing '$INPUT' from MPEG-TS to MPEG-4 ..." >&2
    ffmpeg -i "$INPUT" -c copy "$OUTPUT" || echo "Error: '$INPUT' remux exited with non-zero code: $?" >&2

    rm -f "$INPUT"
  done

  echo 'Pruning short MPEG-4 files ...' >&2
  find -type f -name '*.mp4' -size -128M -print -delete
fi
