#!/bin/bash
set -euo pipefail

###
 # @file
 # This file processes 'stream.online' event notifications.
 #
 # When one of these events is encountered, Streamlink will be started for the
 # user who went online.
 #
 # Check the CONFIG section before using this script.
 ##

################################################################################
#                                   CONFIG                                     #
################################################################################

# Configure where downloaded files will be saved.
DOWNLOAD_DIR="$HOME/archives"

# Configure the naming pattern to use for downloaded files.
NAME='{time:%Y}/{time:%m}/{time:%d}/[{time:%H:%M:%S}] {title} ({id}).ts'

# Configure the OAuth token to pass to the Twitch API (optional).
#
# See https://github.com/clayfreeman/twitch-auth-token-sync for a way that
# developers can automatically get their 'auth-token' cookie value.
AUTH_TOKEN=$(cat "$HOME/.auth-token" 2>/dev/null || true)

# Configure the default arguments for Streamlink.
# The output path will be nested beneath "$FINISHED_DIR/$STREAM".
STREAMLINK_ARGS=(
  --default-stream=best
  --force
  --logdateformat='%Y-%m-%dT%H:%M:%S'
  --logformat='[{asctime}][{name}][{levelname}] {message}'
  --output="$NAME"
  --progress=no
  --retry-max=3
  --retry-open=3
  --retry-streams=3
  --twitch-disable-ads
  --webbrowser=no
)

################################################################################
#                                   SCRIPT                                     #
################################################################################

if STREAM=$(jq -cer 'select(.subscription.type == "stream.online") | .event.broadcaster_user_login')
then
  if ! mkdir -p "$DOWNLOAD_DIR" || ! [ -w "$DOWNLOAD_DIR" ]
  then
    echo "Error: The configured download directory is not writable." >&2
    exit 1
  fi

  if [ -z "$NAME" ]
  then
    echo "Error: The required NAME variable is missing." >&2
    exit 1
  fi

  if [ -z "$STREAMLINK_ARGS" ]
  then
    echo "Error: The required STREAMLINK_ARGS variable is missing." >&2
    exit 1
  fi

  OUTPUT_DIR="$DOWNLOAD_DIR/$STREAM"

  LOCKFILE="$HOME/.$STREAM.lock"
  LOGFILE="$HOME/streamlink.log"

  URL="https://www.twitch.tv/$STREAM"

  if [ -n "${AUTH_TOKEN:-}" ]
  then
    STREAMLINK_ARGS+=(--twitch-api-header=Authorization="OAuth $AUTH_TOKEN")
  fi

  mkdir -p "$OUTPUT_DIR"
  cd "$OUTPUT_DIR"

  exec {LOCK}<>"$LOCKFILE"
  flock -n $LOCK
  trap 'rm -f "$LOCKFILE"' EXIT

  exec &> >(tee -a "$LOGFILE")

  echo "Beginning download of '$URL' ..." >&2
  streamlink "${STREAMLINK_ARGS[@]}" --url="$URL" || echo "Error: Streamlink exited with non-zero code: $?" >&2

  shopt -s globstar nullglob
  for INPUT in **/*.ts
  do
    OUTPUT="${INPUT%.ts}.mp4"

    echo "Changing MPEG-TS container format of '$INPUT' to MPEG-4 ..." >&2
    ffmpeg -i "$INPUT" -c copy "$OUTPUT" || echo "Error: FFmpeg exited with non-zero code: $?" >&2

    rm -f "$INPUT"
  done
fi
